# Server settings
server.port=443
server.error.include-message=always

# SSL configuration
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=12345
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat

# Spring application
spring.application.name=BotZomboid

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost/zombDb
spring.datasource.password=bober
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Telegram bot settings
telegram.webhook-path=https://antanaks.ru/
telegram.bot-name=ZomboidBot
telegram.bot-token=8243614972:AAH01FCx41KBseIGb7AXISmYxg2FAXZXWuw