server:
  port: 34551
  error:
    include-message: always
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: Popa123
    key-store-type: PKCS12

spring:
  application:
    name: BotZomboid
  datasource:
    url: jdbc:postgresql://localhost/zombDb
    password: bober
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

telegram:
  webhook-path: https://95.165.69.170:34551
  bot-name: ZomboidBot
  bot-token: 8243614972:AAH01FCx41KBseIGb7AXISmYxg2FAXZXWuw